cacheFolder: .yarn/cache

enableGlobalCache: false

enableMirror: false

nodeLinker: pnp

#npmScopes:
#  "wapl":
#    npmRegistryServer: "http://192.168.157.52:4872"
#  "solomon":
#    npmRegistryServer: "http://192.168.120.21/api/v4/packages/npm/"
#    npmAlwaysAuth: true
#    npmAuthToken: "pmBddDTgWE4EwGxEv8Rf"

#unsafeHttpWhitelist:
#  - 192.168.157.52
#  - 192.168.120.21

#yarnPath: .yarn/releases/yarn-4.1.0.cjs
